version: '2'
services:
  springbootapp:
    image: springbootappjpa
    container_name: SpringBootApp
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://SpringBootJPADB:3306/db
    ports:
      - 8080:8080

  mysqldb:
    image: mysql
    container_name: SpringBootJPADB
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10